version: '3.8'

services:
    python_dev:
        image: takuver4/python_dev:rev12
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            PYTHONPATH: "/usr/local/lib/python3.10/site-packages:/work/src/ty_lib"
            DISPLAY: host.docker.internal:0.0
        volumes:
            - C:\Users\toruv\OneDrive\work\sample_code:/work/src
            - D:\abuse:/work/overuse
        stdin_open: true
